### ISSUE TITLE
这个支持 koa 吗

### ISSUE THREAD

**Issue by abnerCrack** [qddegtya/passport-ldap#1]
RT

**Comment by qddegtya** [comment]
koa 的版本暂时还没做，不过可以参照这里的实现进行简单的迁移，实际上 koa 和 express 的区别在于从上下文上拿取 req 的逻辑，验证的主要逻辑是不变的，对于包内的 ldap util，也可以直接复用

**Comment by qddegtya** [comment]
@all-contributors add @qddegtya for code,infra,doc,maintenance

**Comment by qddegtya** [comment]
@all-contributors add @qddegtya for code,maintenance,infra

**Comment by qddegtya** [comment]
@all-contributors add @qddegtya for code
